/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    // All artwork is served locally from /public/work (generated by `npm run images`),
    // so no remote hosts need to be allow-listed.
    formats: ['image/avif', 'image/webp'],
  },
};

module.exports = nextConfig;
