/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    // All artwork is served locally from /public/work (generated by `npm run images`),
    // so no remote hosts need to be allow-listed.
    formats: ['image/avif', 'image/webp'],
    // Next 16 no longer ships a default quality allow-list: any `quality` value
    // that isn't declared here logs a warning and falls back. Once `qualities` is
    // set it becomes exhaustive, so the default (75, used by the hero portrait)
    // must be listed too, alongside the grid's 88 and the lightbox's 92.
    qualities: [75, 88, 92],
  },
};

module.exports = nextConfig;
