/**
 * Single source of truth for identity, navigation and contact details.
 * Nothing in this file should be duplicated inside a component.
 */

export interface NavLink {
  label: string;
  href: string;
}

export interface ContactChannel {
  label: string;
  value: string;
  href: string;
  /** Icon key resolved by components/ui/Icon.tsx — never an emoji. */
  icon: 'mail' | 'phone' | 'pin';
}

export const profile = {
  firstName: 'Sowmiya',
  lastName: 'Ravichandran',
  initials: 'SR',
  role: 'Graphic & Interface Designer',
  /** Rendered as the hero statement, one word per line. */
  headline: ['Graphic', '& Interface', 'Designer'],
  location: 'Tirupur, Tamil Nadu',
  availability: 'Available for freelance & full-time',
  /** Kept short on purpose: the work should do the talking. */
  intro:
    'I design retail packaging, print campaigns and brand identities for businesses across Tiruppur and Coimbatore — with a background in textile and embroidery design that taught me to care about craft at millimetre scale.',
  resumeUrl: '/Sowmiya-Ravichandran-Resume.pdf',
  /**
   * Generated by `npm run images` from app/images/portrait.jpg.
   *
   * The source is small (434×351) and already black and white, so it is shown at
   * a modest size and never blown up — an upscaled portrait looks soft and cheap,
   * and undermines the very craftsmanship the page is claiming. If a higher-
   * resolution shot arrives, replace app/images/portrait.jpg, re-run the pipeline
   * and update these dimensions.
   */
  portrait: {
    src: '/portrait.webp',
    alt: 'Sowmiya Ravichandran, photographed in black and white beside a window, one hand resting against the light.',
    width: 434,
    height: 351,
  },
} as const;

export const navLinks: NavLink[] = [
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Experience', href: '#experience' },
  { label: 'Contact', href: '#contact' },
];

export const contactChannels: ContactChannel[] = [
  {
    label: 'Email',
    value: 'sowmiyaravi.design@gmail.com',
    href: 'mailto:sowmiyaravi.design@gmail.com',
    icon: 'mail',
  },
  {
    label: 'Phone',
    value: '+91 90035 23067',
    href: 'tel:+919003523067',
    icon: 'phone',
  },
  {
    label: 'Based in',
    value: 'Tirupur, Tamil Nadu, India',
    href: 'https://www.google.com/maps/search/?api=1&query=Tirupur%2C+Tamil+Nadu',
    icon: 'pin',
  },
];

export const primaryEmail = contactChannels[0].href;

export const seo = {
  title: `${profile.firstName} ${profile.lastName} — ${profile.role}`,
  description:
    'Portfolio of Sowmiya Ravichandran, a graphic and interface designer working across brand identity, print and digital product. Based in Tamil Nadu, India.',
  /** Update once the site has a real domain — used for canonical + OG URLs. */
  url: 'https://sowmiya-portfolio.vercel.app',
} as const;
